import { describe, it, expect } from "vitest";
import {
  authoredCharacters,
  buildExtractionTranscript,
  messageIdentities,
  resolveWatermarkScope,
  selectExtractionSpan,
  spanAuthoredCharacters,
  watermarkThroughEnd,
} from "#src/services/memory/ExtractionWatermark";
import { NOTIFICATION_SOURCES, PROMPT_DELIMITERS } from "#src/constants";

function discordMessage(id: string, text: string): string {
  return (
    `<discord-message id="${id}" author="Gerfs" author-username="imgerf" author-id="150069014368878593" time="2026-09-22T09:39:38-07:00">\n` +
    `<replying-to id="1551996324289978459" author="someone" author-id="599082431592792074"></replying-to>\n` +
    `<content>\n${text}\n</content>\n</discord-message>`
  );
}

const CONVERSATION = [
  { role: "system", content: "You are a coding agent." },
  { role: "user", content: "I deploy the payments service blue-green." },
  { role: "assistant", content: "Noted." },
  {
    role: "assistant",
    content: "",
    toolCalls: [{ id: "call-1", name: "read_file", args: {} }],
  },
  { role: "tool", content: "file contents", tool_call_id: "call-1" },
  { role: "user", content: "We use pnpm, never npm." },
  { role: "assistant", content: "Understood, pnpm only." },
];

describe("messageIdentities", () => {
  it("is the same set before and after persistence swaps content and rawContent", () => {
    const inMemory = {
      role: "user",
      content: "<user-update>\nuse pnpm\n</user-update>",
      rawContent: "use pnpm",
    };
    const persisted = {
      role: "user",
      content: "use pnpm",
      rawContent: "<user-update>\nuse pnpm\n</user-update>",
    };
    expect(new Set(messageIdentities(persisted))).toEqual(
      new Set(messageIdentities(inMemory)),
    );
  });

  it("does not depend on whitespace drift", () => {
    expect(
      messageIdentities({ role: "assistant", content: "Done.\n" }),
    ).toEqual(messageIdentities({ role: "assistant", content: "  Done." }));
  });

  it("separates roles", () => {
    expect(messageIdentities({ role: "user", content: "yes" })).not.toEqual(
      messageIdentities({ role: "assistant", content: "yes" }),
    );
  });

  it("takes the Discord id from the opening tag only — not author-id, not replying-to", () => {
    const identities = messageIdentities({
      role: "user",
      content: discordMessage("1551996407941169222", "hello"),
    });
    const platform = identities.filter((id) => id.startsWith("discord:"));
    expect(platform).toEqual(["discord:1551996407941169222"]);
  });
});

describe("authoredCharacters", () => {
  it("counts only what the user wrote", () => {
    expect(authoredCharacters({ role: "assistant", content: "long reply" })).toBe(0);
    expect(authoredCharacters({ role: "user", content: "use pnpm" })).toBe(8);
  });

  it("counts nothing for harness notifications", () => {
    expect(
      authoredCharacters({
        role: "user",
        content: "Sub-agent finished: the build is green.",
        _notificationSource: NOTIFICATION_SOURCES.ORCHESTRATOR,
      }),
    ).toBe(0);
    expect(
      authoredCharacters({
        role: "user",
        content: `${PROMPT_DELIMITERS.CONTEXT_NOTE_PREFIX} the user switched projects]`,
      }),
    ).toBe(0);
  });

  it("counts a mid-turn user update by its own text, not the wrapper", () => {
    expect(
      authoredCharacters({
        role: "user",
        content: "<user-update>\nuse pnpm\n</user-update>",
        rawContent: "use pnpm",
        _notificationSource: NOTIFICATION_SOURCES.USER_UPDATE,
      }),
    ).toBe(8);
  });

  it("counts a Discord message by its <content>, not its envelope", () => {
    expect(
      authoredCharacters({
        role: "user",
        content: discordMessage("1", "ok"),
      }),
    ).toBe(2);
  });
});

describe("buildExtractionTranscript", () => {
  it("keeps user/assistant text and drops system, tool and tool-call-only turns", () => {
    const { entries, afterSummaryIndex } =
      buildExtractionTranscript(CONVERSATION);
    expect(entries.map((entry) => `${entry.role}: ${entry.text}`)).toEqual([
      "user: I deploy the payments service blue-green.",
      "assistant: Noted.",
      "user: We use pnpm, never npm.",
      "assistant: Understood, pnpm only.",
    ]);
    expect(afterSummaryIndex).toBe(-1);
  });

  it("never extracts from a compaction summary, and remembers where it ended", () => {
    const { entries, afterSummaryIndex } = buildExtractionTranscript([
      { role: "system", content: "You are a coding agent." },
      {
        role: "user",
        content: `${PROMPT_DELIMITERS.CONVERSATION_SUMMARY_PREFIX} — auto-generated by compaction]\n\nEarlier: blue-green.`,
        isCompactSummary: true,
      },
      { role: "user", content: "We use pnpm, never npm." },
      { role: "assistant", content: "Understood, pnpm only." },
    ]);
    expect(entries.map((entry) => entry.text)).toEqual([
      "We use pnpm, never npm.",
      "Understood, pnpm only.",
    ]);
    expect(afterSummaryIndex).toBe(0);
  });
});

describe("selectExtractionSpan", () => {
  const firstTranscript = buildExtractionTranscript(CONVERSATION);
  const firstWatermark = watermarkThroughEnd(firstTranscript)!;
  const grown = [
    ...CONVERSATION,
    { role: "user", content: "I prefer oklch colours." },
    { role: "assistant", content: "oklch it is." },
  ];

  it("reads everything the first time", () => {
    const selection = selectExtractionSpan(firstTranscript, null);
    expect(selection.reason).toBe("first");
    expect(selection.context).toEqual([]);
    expect(selection.span).toHaveLength(4);
  });

  it("reads only what came after the watermark, with a fixed context window before it", () => {
    const selection = selectExtractionSpan(
      buildExtractionTranscript(grown),
      firstWatermark,
      2,
    );
    expect(selection.reason).toBe("watermark");
    expect(selection.context.map((entry) => entry.text)).toEqual([
      "We use pnpm, never npm.",
      "Understood, pnpm only.",
    ]);
    expect(selection.span.map((entry) => entry.text)).toEqual([
      "I prefer oklch colours.",
      "oklch it is.",
    ]);
  });

  it("finds the watermark after persistence swapped content and rawContent", () => {
    const inMemory = [
      { role: "user", content: "<user-update>\nuse pnpm, never npm\n</user-update>", rawContent: "use pnpm, never npm" },
      { role: "assistant", content: "Understood." },
      { role: "user", content: "more" },
      { role: "assistant", content: "ok" },
    ];
    const watermark = watermarkThroughEnd(buildExtractionTranscript(inMemory))!;
    const reloaded = [
      { role: "user", content: "use pnpm, never npm", rawContent: "<user-update>\nuse pnpm, never npm\n</user-update>" },
      { role: "assistant", content: "Understood." },
      { role: "user", content: "more" },
      { role: "assistant", content: "ok" },
      { role: "user", content: "the next thing" },
    ];
    const selection = selectExtractionSpan(
      buildExtractionTranscript(reloaded),
      watermark,
    );
    expect(selection.reason).toBe("watermark");
    expect(selection.span.map((entry) => entry.text)).toEqual(["the next thing"]);
  });

  it("does not stop at a later repeat of a short reply — the anchor disambiguates", () => {
    const history = [
      { role: "user", content: "Rename the flag." },
      { role: "assistant", content: "Done." },
    ];
    const watermark = watermarkThroughEnd(buildExtractionTranscript(history))!;
    const later = [
      ...history,
      { role: "user", content: "I am moving to Victoria next month." },
      { role: "assistant", content: "Done." },
    ];
    const selection = selectExtractionSpan(
      buildExtractionTranscript(later),
      watermark,
    );
    expect(selection.span.map((entry) => entry.text)).toEqual([
      "I am moving to Victoria next month.",
      "Done.",
    ]);
  });

  it("falls back to the Discord id when the bot's own reply came back reworded", () => {
    const firstCall = [
      { role: "user", content: discordMessage("100", "who won?") },
      { role: "user", content: discordMessage("101", "I support the Canucks") },
      { role: "assistant", content: "<@1> the Canucks, obviously." },
    ];
    const watermark = watermarkThroughEnd(buildExtractionTranscript(firstCall))!;
    expect(watermark.platformThroughMessageId).toBe("discord:101");
    const secondCall = [
      { role: "user", content: discordMessage("100", "who won?") },
      { role: "user", content: discordMessage("101", "I support the Canucks") },
      // Discord rendered the mention differently in the next history.
      { role: "assistant", content: "@quark the Canucks, obviously." },
      { role: "user", content: discordMessage("102", "I moved to Toronto last year") },
    ];
    const selection = selectExtractionSpan(
      buildExtractionTranscript(secondCall),
      watermark,
    );
    expect(selection.reason).toBe("platform-id");
    expect(selection.span.map((entry) => entry.role)).toEqual([
      "assistant",
      "user",
    ]);
    expect(selection.span[1].text).toContain("Toronto");
  });

  it("after compaction summarized the watermark away, reads everything after the summary", () => {
    const compacted = [
      { role: "system", content: "You are a coding agent." },
      {
        role: "user",
        content: `${PROMPT_DELIMITERS.CONVERSATION_SUMMARY_PREFIX} — auto-generated by compaction]\n\nblue-green, pnpm`,
        isCompactSummary: true,
      },
      { role: "user", content: "I prefer oklch colours." },
      { role: "assistant", content: "oklch it is." },
    ];
    const selection = selectExtractionSpan(
      buildExtractionTranscript(compacted),
      firstWatermark,
    );
    expect(selection.reason).toBe("after-compaction");
    expect(selection.context).toEqual([]);
    expect(selection.span.map((entry) => entry.text)).toEqual([
      "I prefer oklch colours.",
      "oklch it is.",
    ]);
  });

  it("re-reads the whole transcript when the watermark message was edited away", () => {
    const edited = [
      { role: "user", content: "I deploy the payments service blue-green." },
      { role: "assistant", content: "Noted." },
      { role: "user", content: "We use yarn now." },
      { role: "assistant", content: "Understood, yarn." },
    ];
    const selection = selectExtractionSpan(
      buildExtractionTranscript(edited),
      firstWatermark,
    );
    expect(selection.reason).toBe("watermark-lost");
    expect(selection.span).toHaveLength(4);
  });

  it("sums the user-written characters of a span", () => {
    const selection = selectExtractionSpan(
      buildExtractionTranscript(grown),
      firstWatermark,
    );
    expect(spanAuthoredCharacters(selection.span)).toBe(
      "I prefer oklch colours.".length,
    );
  });
});

describe("resolveWatermarkScope", () => {
  const base = { project: "lupos", agent: "LUPOS", profileId: "default" };

  it("keys a platform turn by its channel, not its (per-reply) conversation", () => {
    const scope = resolveWatermarkScope({
      ...base,
      conversationId: "conversation-a",
      agentContext: { platform: "discord", guildId: "g1", channelId: "c1" },
    });
    expect(scope?.scope).toBe("channel:discord:g1:c1");
    expect(scope?.key).toBe("lupos|LUPOS|default|channel:discord:g1:c1");
  });

  it("keys any other turn by its conversation", () => {
    expect(
      resolveWatermarkScope({ ...base, conversationId: "conversation-a" })
        ?.scope,
    ).toBe("conversation:conversation-a");
    expect(
      resolveWatermarkScope({
        ...base,
        conversationId: "conversation-a",
        agentContext: { platform: "discord", guildId: "g1", channelId: null },
      })?.scope,
    ).toBe("conversation:conversation-a");
  });

  it("separates memory scopes that share a channel", () => {
    const channel = { platform: "discord", guildId: "g1", channelId: "c1" };
    const lupos = resolveWatermarkScope({ ...base, agentContext: channel });
    const other = resolveWatermarkScope({
      ...base,
      agent: "MEEPO",
      agentContext: channel,
    });
    expect(lupos?.key).not.toBe(other?.key);
  });

  it("has no scope without a conversation or channel", () => {
    expect(resolveWatermarkScope(base)).toBeNull();
  });
});
